/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.autoplus.frame;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author anouer
 */
public class AcceuilGui extends javax.swing.JFrame {
public static String t3;
      Connection conn=null;
      ResultSet rs = null ;
      PreparedStatement ps = null;
    /**
     * Creates new form AcceuilGui
     */
    public AcceuilGui() {
        initComponents();
        datecourante() ;
        this.setIconImage(new ImageIcon(getClass().getResource("logocar.png")).getImage());
    conn = ConexionBD.Conexion();
    recuperutlisateur();
    }
    public void datecourante() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar Cal = new GregorianCalendar();

                    int sconde = Cal.get(Calendar.SECOND);
                    int minute = Cal.get(Calendar.MINUTE);
                    int heure = Cal.get(Calendar.HOUR);
                    int AM_PM = Cal.get(Calendar.AM_PM);  
                    String pa;
                    if(AM_PM==1){
                        pa="PM";
                    }else{
                        pa="AM";
                    }
                    
                         
                    labDate.setText( + heure + ":" + (minute) + ":" + sconde +" "+pa  );
                    
                 int mois = Cal.get(Calendar.MONTH);
                    int annee = Cal.get(Calendar.YEAR);
                    int jour = Cal.get(Calendar.DAY_OF_MONTH);

                    labdate2.setText( + jour + "/" + (mois+1) + "/" + annee);              
                    
                    
                    try {
                        sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }

        };
        
clock.start();
    }
    
    
   public void recuperutlisateur(){
    LoginGUI lo =new LoginGUI();
    
try {
    String recp = lo.utilisateur();
    String requet = "select * from login_table where login = '" + recp + "'";
            ps = conn.prepareStatement(requet);
            rs = ps.executeQuery();
            if (rs.next()) {
                String t2 = rs.getString("prenom");
//                lprenom.setText(t2);
            String t1 = rs.getString("nom");
                lnom.setText(t1+" "+t2);
                this.t3 = rs.getString("type");
                type.setText(t3);
                if (t3.equals("Adminstrateur")) {
//        formationbtn.setVisible(false);
//        examenbtn.setVisible(false);
//        payementbtn.setVisible(false);
    }else if(t3.equals("Secrétaire")){
//        utlisateurbtn.setVisible(false);
//        vehiculebtn.setVisible(false);
//        moniteurbtn.setVisible(false);
//        depensebtn.setVisible(false);
//        tarifbtn.setVisible(false);
//        parametre.setVisible(false);
    }
       ps.close();
                rs.close();         
            }
}catch (Exception e) {
            System.out.println(e);
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
} 
    
    public String utilisateurs() {
        return t3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labdate2 = new javax.swing.JLabel();
        logomax = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menublanc = new javax.swing.JLabel();
        Accueil = new javax.swing.JLabel();
        menublue = new javax.swing.JLabel();
        desk = new javax.swing.JDesktopPane();
        type = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        examenbtn = new javax.swing.JButton();
        moniteurbtn = new javax.swing.JButton();
        utlisateurbtn = new javax.swing.JButton();
        tarifbtn = new javax.swing.JButton();
        depensebtn = new javax.swing.JButton();
        vehiculebtn = new javax.swing.JButton();
        candidatbtn = new javax.swing.JButton();
        formationbtn = new javax.swing.JButton();
        parametre = new javax.swing.JButton();
        payementbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 380));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        labDate.setFont(new java.awt.Font("DS-Digital", 1, 24)); // NOI18N
        labDate.setForeground(new java.awt.Color(255, 255, 255));
        labDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDate.setText("10:15:30 PM");
        getContentPane().add(labDate);
        labDate.setBounds(570, 30, 180, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/info.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1170, 30, 34, 30);

        labdate2.setFont(new java.awt.Font("FreeSerif", 0, 14)); // NOI18N
        labdate2.setForeground(new java.awt.Color(255, 255, 255));
        labdate2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labdate2.setText("12/02/2016");
        getContentPane().add(labdate2);
        labdate2.setBounds(730, 30, 140, 30);

        logomax.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        logomax.setForeground(new java.awt.Color(0, 0, 153));
        logomax.setText("Auto Max");
        getContentPane().add(logomax);
        logomax.setBounds(10, 0, 160, 20);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Gestion Auto Ecole TN");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 140, 10);

        menublanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/menu.png"))); // NOI18N
        getContentPane().add(menublanc);
        menublanc.setBounds(0, 0, 1370, 30);

        Accueil.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Accueil.setForeground(new java.awt.Color(255, 255, 255));
        Accueil.setText("Accueil");
        Accueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccueilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccueilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccueilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AccueilMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AccueilMouseReleased(evt);
            }
        });
        getContentPane().add(Accueil);
        Accueil.setBounds(20, 30, 80, 30);

        menublue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/Menu2.png"))); // NOI18N
        getContentPane().add(menublue);
        menublue.setBounds(0, 30, 1370, 30);

        desk.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(desk);
        desk.setBounds(190, 90, 1010, 620);

        type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(type);
        type.setBounds(520, 70, 140, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(":");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(660, 70, 10, 17);

        lnom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lnom.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lnom);
        lnom.setBounds(670, 70, 320, 20);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 3, 18))); // NOI18N

        examenbtn.setBackground(new java.awt.Color(225, 225, 225));
        examenbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        examenbtn.setForeground(new java.awt.Color(255, 255, 255));
        examenbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/icon.png"))); // NOI18N
        examenbtn.setText("Examens");
        examenbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(102, 0, 102)));
        examenbtn.setContentAreaFilled(false);
        examenbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examenbtn.setOpaque(true);
        examenbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                examenbtnMouseReleased(evt);
            }
        });
        examenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examenbtnActionPerformed(evt);
            }
        });

        moniteurbtn.setBackground(new java.awt.Color(225, 225, 225));
        moniteurbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        moniteurbtn.setForeground(new java.awt.Color(255, 255, 255));
        moniteurbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/black-user-shape.png"))); // NOI18N
        moniteurbtn.setText("Moniteurs");
        moniteurbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(153, 0, 0)));
        moniteurbtn.setContentAreaFilled(false);
        moniteurbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moniteurbtn.setOpaque(true);
        moniteurbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moniteurbtnMouseReleased(evt);
            }
        });
        moniteurbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moniteurbtnActionPerformed(evt);
            }
        });

        utlisateurbtn.setBackground(new java.awt.Color(225, 225, 225));
        utlisateurbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        utlisateurbtn.setForeground(new java.awt.Color(255, 255, 255));
        utlisateurbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/user.png"))); // NOI18N
        utlisateurbtn.setText("Utilisateurs");
        utlisateurbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 102, 102)));
        utlisateurbtn.setContentAreaFilled(false);
        utlisateurbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        utlisateurbtn.setOpaque(true);
        utlisateurbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                utlisateurbtnMouseReleased(evt);
            }
        });
        utlisateurbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utlisateurbtnActionPerformed(evt);
            }
        });

        tarifbtn.setBackground(new java.awt.Color(225, 225, 225));
        tarifbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tarifbtn.setForeground(new java.awt.Color(255, 255, 255));
        tarifbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/online-payment.png"))); // NOI18N
        tarifbtn.setText("Tarifs");
        tarifbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(102, 102, 0)));
        tarifbtn.setContentAreaFilled(false);
        tarifbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tarifbtn.setOpaque(true);
        tarifbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tarifbtnMouseReleased(evt);
            }
        });
        tarifbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifbtnActionPerformed(evt);
            }
        });

        depensebtn.setBackground(new java.awt.Color(225, 225, 225));
        depensebtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        depensebtn.setForeground(new java.awt.Color(255, 255, 255));
        depensebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/diagram.png"))); // NOI18N
        depensebtn.setText("Depenses&Revenus");
        depensebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(51, 153, 0)));
        depensebtn.setContentAreaFilled(false);
        depensebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depensebtn.setOpaque(true);
        depensebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                depensebtnMouseReleased(evt);
            }
        });
        depensebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depensebtnActionPerformed(evt);
            }
        });

        vehiculebtn.setBackground(new java.awt.Color(225, 225, 225));
        vehiculebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vehiculebtn.setForeground(new java.awt.Color(255, 255, 255));
        vehiculebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/taxi.png"))); // NOI18N
        vehiculebtn.setText("Vehicule");
        vehiculebtn.setToolTipText("");
        vehiculebtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(204, 102, 0)));
        vehiculebtn.setContentAreaFilled(false);
        vehiculebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vehiculebtn.setOpaque(true);
        vehiculebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                vehiculebtnMouseReleased(evt);
            }
        });
        vehiculebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculebtnActionPerformed(evt);
            }
        });

        candidatbtn.setBackground(new java.awt.Color(225, 225, 225));
        candidatbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        candidatbtn.setForeground(new java.awt.Color(255, 255, 255));
        candidatbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/multiple-users-silhouette.png"))); // NOI18N
        candidatbtn.setText("Candidats");
        candidatbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 0, 153)));
        candidatbtn.setContentAreaFilled(false);
        candidatbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        candidatbtn.setOpaque(true);
        candidatbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                candidatbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                candidatbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                candidatbtnMouseReleased(evt);
            }
        });
        candidatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatbtnActionPerformed(evt);
            }
        });

        formationbtn.setBackground(new java.awt.Color(225, 225, 225));
        formationbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        formationbtn.setForeground(new java.awt.Color(255, 255, 255));
        formationbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/teacher-pointing-blackboard.png"))); // NOI18N
        formationbtn.setText("Formations");
        formationbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 102, 0)));
        formationbtn.setContentAreaFilled(false);
        formationbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        formationbtn.setMinimumSize(new java.awt.Dimension(69, 23));
        formationbtn.setOpaque(true);
        formationbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formationbtnMouseReleased(evt);
            }
        });
        formationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formationbtnActionPerformed(evt);
            }
        });

        parametre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        parametre.setForeground(new java.awt.Color(255, 255, 255));
        parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/settings-gears.png"))); // NOI18N
        parametre.setText("Parametere");
        parametre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(204, 0, 0)));
        parametre.setContentAreaFilled(false);
        parametre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parametre.setOpaque(true);
        parametre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parametreMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                parametreMouseReleased(evt);
            }
        });
        parametre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametreActionPerformed(evt);
            }
        });

        payementbtn.setBackground(new java.awt.Color(225, 225, 225));
        payementbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        payementbtn.setForeground(new java.awt.Color(255, 255, 255));
        payementbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/autoplus/images/get-money.png"))); // NOI18N
        payementbtn.setText("Paiements");
        payementbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(204, 0, 0)));
        payementbtn.setContentAreaFilled(false);
        payementbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payementbtn.setOpaque(true);
        payementbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payementbtnMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                payementbtnMouseReleased(evt);
            }
        });
        payementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payementbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(candidatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moniteurbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utlisateurbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiculebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depensebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarifbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parametre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payementbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(candidatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(moniteurbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(utlisateurbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(formationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehiculebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(depensebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(examenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tarifbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payementbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parametre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jDesktopPane1.setLayer(examenbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(moniteurbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(utlisateurbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tarifbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(depensebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(vehiculebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(candidatbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(formationbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(parametre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(payementbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(10, 130, 164, 540);

        setSize(new java.awt.Dimension(1382, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void candidatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidatbtnActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Liste_des_Candidats lc = new Liste_des_Candidats();
        this.desk.add(lc);
        try {
            lc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        lc.show();
    }//GEN-LAST:event_candidatbtnActionPerformed

    private void formationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formationbtnActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Formation fr = new Formation();
        this.desk.add(fr);
        try {
            fr.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        fr.show();
    }//GEN-LAST:event_formationbtnActionPerformed

    private void examenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examenbtnActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        
        Examens ex = new Examens();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_examenbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.desk.removeAll();
        this.desk.repaint();
        
        Notes nt = new Notes();
        this.desk.add(nt);
        
        try {
            nt.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        nt.show();
    }//GEN-LAST:event_formWindowOpened

    private void payementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payementbtnActionPerformed
     this.desk.removeAll();
        this.desk.repaint();
        
        Payement pt = new Payement();
        this.desk.add(pt);
        
        try {
            pt.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        pt.show();
    }//GEN-LAST:event_payementbtnActionPerformed

    private void AccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMouseClicked
        this.desk.removeAll();
        this.desk.repaint();
        
        Notes nt = new Notes();
        this.desk.add(nt);
        
        try {
            nt.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        nt.show();
    }//GEN-LAST:event_AccueilMouseClicked

    private void AccueilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMouseEntered
        Accueil.setForeground(Color.LIGHT_GRAY);
      
    }//GEN-LAST:event_AccueilMouseEntered

    private void AccueilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMouseExited
        Accueil.setForeground(Color.WHITE);
       
    }//GEN-LAST:event_AccueilMouseExited

    private void AccueilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMousePressed
       Accueil.setForeground(Color.WHITE);
       
    }//GEN-LAST:event_AccueilMousePressed

    private void AccueilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilMouseReleased
       Accueil.setForeground(Color.LIGHT_GRAY);
         candidatbtn.setBackground(new java.awt.Color(225,225,225)); 
      formationbtn.setBackground(new java.awt.Color(225,225,225));
      moniteurbtn.setBackground(new java.awt.Color(225,225,225));
       examenbtn.setBackground(new java.awt.Color(225,225,225));
       utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
        payementbtn.setBackground(new java.awt.Color(225,225,225));
        vehiculebtn.setBackground(new java.awt.Color(225,225,225));
         depensebtn.setBackground(new java.awt.Color(225,225,225));
          tarifbtn.setBackground(new java.awt.Color(225,225,225));
          parametre.setBackground(new java.awt.Color(225,225,225));
       
    }//GEN-LAST:event_AccueilMouseReleased

    private void moniteurbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moniteurbtnActionPerformed
       this.desk.removeAll();
        this.desk.repaint();
        
        Moniteur ex = new Moniteur();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_moniteurbtnActionPerformed

    private void utlisateurbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utlisateurbtnActionPerformed
      this.desk.removeAll();
        this.desk.repaint();
        
        Utilisateur ex = new Utilisateur();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_utlisateurbtnActionPerformed

    private void vehiculebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculebtnActionPerformed
       this.desk.removeAll();
        this.desk.repaint();
        
        Vehicule ex = new Vehicule();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_vehiculebtnActionPerformed

    private void tarifbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifbtnActionPerformed
      this.desk.removeAll();
        this.desk.repaint();
        
        Tarifs ex = new Tarifs();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_tarifbtnActionPerformed

    private void depensebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depensebtnActionPerformed
         this.desk.removeAll();
        this.desk.repaint();
        
        Depenses ex = new Depenses();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_depensebtnActionPerformed

    private void candidatbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidatbtnMouseReleased
      candidatbtn.setBackground(new java.awt.Color(51,153,255)); 
      formationbtn.setBackground(new java.awt.Color(225,225,225));
      moniteurbtn.setBackground(new java.awt.Color(225,225,225));
       examenbtn.setBackground(new java.awt.Color(225,225,225));
       utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
        payementbtn.setBackground(new java.awt.Color(225,225,225));
        vehiculebtn.setBackground(new java.awt.Color(225,225,225));
         depensebtn.setBackground(new java.awt.Color(225,225,225));
          tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_candidatbtnMouseReleased

    private void formationbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formationbtnMouseReleased
           candidatbtn.setBackground(new java.awt.Color(225,225,225)); 
           formationbtn.setBackground(new java.awt.Color(0,204,04));
           moniteurbtn.setBackground(new java.awt.Color(225,225,225));
            examenbtn.setBackground(new java.awt.Color(225,225,225));
             utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
                payementbtn.setBackground(new java.awt.Color(225,225,225));
                vehiculebtn.setBackground(new java.awt.Color(225,225,225));
                  depensebtn.setBackground(new java.awt.Color(225,225,225));
                   tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_formationbtnMouseReleased

    private void candidatbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidatbtnMouseEntered
//     candidatbtn.setBackground(new java.awt.Color(51,2,255));
    }//GEN-LAST:event_candidatbtnMouseEntered

    private void candidatbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidatbtnMouseExited
//        candidatbtn.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_candidatbtnMouseExited

    private void moniteurbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moniteurbtnMouseReleased
    moniteurbtn.setBackground(new java.awt.Color(255,51,51));
    candidatbtn.setBackground(new java.awt.Color(225,225,225));
     formationbtn.setBackground(new java.awt.Color(225,225,225));
         examenbtn.setBackground(new java.awt.Color(225,225,225));
          utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
             payementbtn.setBackground(new java.awt.Color(225,225,225));
             vehiculebtn.setBackground(new java.awt.Color(225,225,225));
              depensebtn.setBackground(new java.awt.Color(225,225,225));
               tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_moniteurbtnMouseReleased

    private void examenbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examenbtnMouseReleased
         moniteurbtn.setBackground(new java.awt.Color(225,225,225));
    candidatbtn.setBackground(new java.awt.Color(225,225,225));
     formationbtn.setBackground(new java.awt.Color(225,225,225));
     examenbtn.setBackground(new java.awt.Color(204,0,255));
      utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
          payementbtn.setBackground(new java.awt.Color(225,225,225));
          vehiculebtn.setBackground(new java.awt.Color(225,225,225));
           depensebtn.setBackground(new java.awt.Color(225,225,225));
            tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_examenbtnMouseReleased

    private void utlisateurbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utlisateurbtnMouseReleased
       moniteurbtn.setBackground(new java.awt.Color(225,225,225));
    candidatbtn.setBackground(new java.awt.Color(225,225,225));
     formationbtn.setBackground(new java.awt.Color(225,225,225));
     examenbtn.setBackground(new java.awt.Color(225,225,225));
     utlisateurbtn.setBackground(new java.awt.Color(0,153,153));
    payementbtn.setBackground(new java.awt.Color(225,225,225));
    vehiculebtn.setBackground(new java.awt.Color(225,225,225));
     depensebtn.setBackground(new java.awt.Color(225,225,225));
      tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_utlisateurbtnMouseReleased

    private void payementbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payementbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_payementbtnMouseReleased

    private void payementbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payementbtnMouseClicked
       moniteurbtn.setBackground(new java.awt.Color(225,225,225));
    candidatbtn.setBackground(new java.awt.Color(225,225,225));
     formationbtn.setBackground(new java.awt.Color(225,225,225));
     examenbtn.setBackground(new java.awt.Color(225,225,225));
     utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
      payementbtn.setBackground(new java.awt.Color(255,0,0));
        vehiculebtn.setBackground(new java.awt.Color(225,225,225));
         tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_payementbtnMouseClicked

    private void vehiculebtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiculebtnMouseReleased
     moniteurbtn.setBackground(new java.awt.Color(225,225,225));
    candidatbtn.setBackground(new java.awt.Color(225,225,225));
     formationbtn.setBackground(new java.awt.Color(225,225,225));
     examenbtn.setBackground(new java.awt.Color(225,225,225));
     utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
      payementbtn.setBackground(new java.awt.Color(225,225,225));
       vehiculebtn.setBackground(new java.awt.Color(255,153,0));
       depensebtn.setBackground(new java.awt.Color(225,225,225));
        tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_vehiculebtnMouseReleased

    private void depensebtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depensebtnMouseReleased
     moniteurbtn.setBackground(new java.awt.Color(225,225,225));
    candidatbtn.setBackground(new java.awt.Color(225,225,225));
     formationbtn.setBackground(new java.awt.Color(225,225,225));
     examenbtn.setBackground(new java.awt.Color(225,225,225));
     utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
      payementbtn.setBackground(new java.awt.Color(225,225,225));
       vehiculebtn.setBackground(new java.awt.Color(225,225,225));
       depensebtn.setBackground(new java.awt.Color(51,204,0));
        tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_depensebtnMouseReleased

    private void tarifbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarifbtnMouseReleased
       moniteurbtn.setBackground(new java.awt.Color(225,225,225));
    candidatbtn.setBackground(new java.awt.Color(225,225,225));
     formationbtn.setBackground(new java.awt.Color(225,225,225));
     examenbtn.setBackground(new java.awt.Color(225,225,225));
     utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
      payementbtn.setBackground(new java.awt.Color(225,225,225));
       vehiculebtn.setBackground(new java.awt.Color(225,225,225));
       depensebtn.setBackground(new java.awt.Color(225,225,225));
        tarifbtn.setBackground(new java.awt.Color(153,153,0));
    }//GEN-LAST:event_tarifbtnMouseReleased

    private void parametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parametreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_parametreMouseClicked

    private void parametreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parametreMouseReleased
         candidatbtn.setBackground(new java.awt.Color(225,225,225)); 
      formationbtn.setBackground(new java.awt.Color(225,225,225));
      moniteurbtn.setBackground(new java.awt.Color(225,225,225));
       examenbtn.setBackground(new java.awt.Color(225,225,225));
       utlisateurbtn.setBackground(new java.awt.Color(225,225,225));
        payementbtn.setBackground(new java.awt.Color(225,225,225));
        vehiculebtn.setBackground(new java.awt.Color(225,225,225));
         depensebtn.setBackground(new java.awt.Color(225,225,225));
          tarifbtn.setBackground(new java.awt.Color(225,225,225));
          parametre.setBackground(new java.awt.Color(102,102,0));
    }//GEN-LAST:event_parametreMouseReleased

    private void parametreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametreActionPerformed
        this.desk.removeAll();
        this.desk.repaint();
        
        Parametre ex = new Parametre();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_parametreActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String v ="<html><head></head><body><h3 color ='#2C4CCC'><center>"
            + "<br><p><b><i>Auto Max </i></b>"
            + "<br><p><b><i>Logiciel de gestion D'auto Ecole</i></b><br></p><br>"
        + "<br><p ><b><i>Tous droit reservé</i></b></p><br>"
        + "<br><p >2015-2016</i></b></p><br>"
        + "<br><p >---------<b><i>"+"</i></b></p><br></center></h3></p></body></html>";
    JOptionPane p =new JOptionPane();
    p.setMessage(v);
    p.setMessageType(JOptionPane.INFORMATION_MESSAGE);
    JDialog d =p.createDialog(null,"Information sur le logiciel ");
    d.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accueil;
    private javax.swing.JButton candidatbtn;
    private javax.swing.JButton depensebtn;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JButton examenbtn;
    private javax.swing.JButton formationbtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labdate2;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel logomax;
    private javax.swing.JLabel menublanc;
    private javax.swing.JLabel menublue;
    private javax.swing.JButton moniteurbtn;
    private javax.swing.JButton parametre;
    private javax.swing.JButton payementbtn;
    private javax.swing.JButton tarifbtn;
    private javax.swing.JLabel type;
    private javax.swing.JButton utlisateurbtn;
    private javax.swing.JButton vehiculebtn;
    // End of variables declaration//GEN-END:variables
}
