/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.autoplus.frame;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author anouer
 */
public class Ajoutregelement extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    /**
     * Creates new form Ajoutregelement
     */
    public Ajoutregelement() {
        initComponents();
        conn = ConexionBD.Conexion();
        Recuper();
        moderegel.setVisible(false);
        cheq.setVisible(false);
        lreste.setVisible(false);
        jLabel7.setVisible(false);
        txtmttotal.setVisible(false);
    }

    public void Recuper() {
        Payement info = new Payement();
        info.Deplace();
        info.calcultotal();
        info.claculreste();
        String recv = info.gettableresults();
        try {
            String rec = info.gettableresulto();
            String requet = "select * from candidat_table where cin = '" + rec + "'";
            ps = conn.prepareStatement(requet);
            rs = ps.executeQuery();
            if (rs.next()) {
                String t1 = rs.getString("cin");
                txtcin.setText(t1);
                String t2 = rs.getString("nomc");
                txtnom.setText(t2);
                String t = rs.getString("prenomc");
                txtprenom.setText(t);
                String t3 = rs.getString("date_naissance");
                dts.setText(t3);

                //JOptionPane.showMessageDialog(null, vbn);
//                txtsexe.setText(t5);
                String t6 = rs.getString("gsm");
                txtgsm.setText(t6);
                 String t12 = rs.getString("typeiscri");
                txtpermis.setText(t12);

            }
            System.out.println(recv);
//            String resultatcvc = String.valueOf(recv);
            txtmttotal.setText(recv);
        } catch (Exception e) {
            System.out.println(e);
        }

//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcin = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        datereglement = new com.toedter.calendar.JDateChooser();
        ajoutbtnok = new javax.swing.JButton();
        txtgsm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dts = new javax.swing.JTextField();
        txtmttotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmontantc = new javax.swing.JTextField();
        moderegel = new javax.swing.JTextField();
        combomode = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lreste = new javax.swing.JLabel();
        cheq = new javax.swing.JLabel();
        txtpermis = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(746, 468));
        getContentPane().setLayout(null);

        jLabel1.setText("cin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 13, 14);

        txtcin.setEditable(false);
        txtcin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcinActionPerformed(evt);
            }
        });
        getContentPane().add(txtcin);
        txtcin.setBounds(110, 50, 160, 20);

        txtnom.setEditable(false);
        getContentPane().add(txtnom);
        txtnom.setBounds(110, 90, 160, 20);

        jLabel3.setText("nom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 20, 14);

        jLabel4.setText("prenom");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 36, 14);

        txtprenom.setEditable(false);
        getContentPane().add(txtprenom);
        txtprenom.setBounds(110, 120, 160, 20);

        datereglement.setDateFormatString("yyyy-MM-dd");
        datereglement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                datereglementMouseReleased(evt);
            }
        });
        datereglement.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                datereglementComponentAdded(evt);
            }
        });
        datereglement.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datereglementAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        datereglement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datereglementKeyReleased(evt);
            }
        });
        getContentPane().add(datereglement);
        datereglement.setBounds(430, 60, 180, 20);

        ajoutbtnok.setText("Ajouter");
        ajoutbtnok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutbtnokMouseClicked(evt);
            }
        });
        ajoutbtnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutbtnokActionPerformed(evt);
            }
        });
        getContentPane().add(ajoutbtnok);
        ajoutbtnok.setBounds(240, 350, 120, 60);

        txtgsm.setEditable(false);
        txtgsm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgsmKeyTyped(evt);
            }
        });
        getContentPane().add(txtgsm);
        txtgsm.setBounds(110, 160, 160, 20);

        jLabel5.setText("GSM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 160, 21, 14);

        jLabel6.setText("Permis :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 50, 14);

        dts.setEditable(false);
        getContentPane().add(dts);
        dts.setBounds(130, 200, 150, 20);
        getContentPane().add(txtmttotal);
        txtmttotal.setBounds(430, 180, 180, 20);

        jLabel7.setText("Reste à réglé");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 190, 90, 14);

        jLabel8.setText("Montant :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 90, 60, 14);

        txtmontantc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmontantcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontantcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontantcKeyTyped(evt);
            }
        });
        getContentPane().add(txtmontantc);
        txtmontantc.setBounds(430, 90, 180, 20);
        getContentPane().add(moderegel);
        moderegel.setBounds(430, 150, 180, 20);

        combomode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Espces", "Chéque" }));
        combomode.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combomodePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(combomode);
        combomode.setBounds(430, 120, 180, 20);

        jLabel9.setText("Mode de réglement :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 120, 110, 20);

        jLabel10.setText("Date de réglement :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 60, 110, 20);
        getContentPane().add(lreste);
        lreste.setBounds(630, 90, 90, 20);

        cheq.setText("N° Chéque :");
        getContentPane().add(cheq);
        cheq.setBounds(310, 150, 90, 14);

        txtpermis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpermis.setForeground(new java.awt.Color(0, 0, 153));
        txtpermis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtpermis);
        txtpermis.setBounds(110, 240, 90, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(300, 44, 330, 250);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder("Régelement :"));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 30, 280, 274);

        jLabel11.setText("Date Naissance :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 200, 90, 14);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcinActionPerformed

    private void datereglementMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datereglementMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datereglementMouseReleased

    private void datereglementComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_datereglementComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datereglementComponentAdded

    private void datereglementAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datereglementAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_datereglementAncestorAdded

    private void datereglementKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datereglementKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datereglementKeyReleased

    private void ajoutbtnokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutbtnokMouseClicked

    }//GEN-LAST:event_ajoutbtnokMouseClicked

    private void ajoutbtnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutbtnokActionPerformed
//        Date actuelle = new Date();
//        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        String date = dateFormat.format(actuelle);
//        String dc = date;
        String tmode = (String) combomode.getSelectedItem();
        try {

            String requete = "insert into regelement (cinct,datereg ,mtreg,mode,numche,typesp) values (?,?,?,'" + tmode + "',?,?)";
            ps = conn.prepareStatement(requete);
            ps.setString(1, txtcin.getText());
            ps.setString(2, ((JTextField) datereglement.getDateEditor().getUiComponent()).getText());
            ps.setString(3, txtmontantc.getText());

            ps.setString(4, moderegel.getText());
            ps.setString(5, txtpermis.getText());
            ps.execute();

            JOptionPane.showMessageDialog(null, "Enregistrement avec succès");

            dispose();

        } catch (Exception e) {
            System.out.println("--> SQLException : " + e);
            JOptionPane.showMessageDialog(null, "Tout est Obligatoire");
        } finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "deja inserre");
            }
        }
    }//GEN-LAST:event_ajoutbtnokActionPerformed

    private void txtgsmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgsmKeyTyped
        char t = evt.getKeyChar();
        if (!(Character.isDigit(t) || (t == KeyEvent.VK_BACK_SPACE) || (t == KeyEvent.VK_DELETE))) {
            evt.consume();
        }

    }//GEN-LAST:event_txtgsmKeyTyped

    private void txtmontantcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontantcKeyTyped
        char t = evt.getKeyChar();
        if (!(Character.isDigit(t) || (t == KeyEvent.VK_BACK_SPACE) || (t == KeyEvent.VK_DELETE))) {
            evt.consume();

        }
    }//GEN-LAST:event_txtmontantcKeyTyped

    private void txtmontantcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontantcKeyReleased
        try {
            String tbt = txtmttotal.getText();
            String tbst = txtmontantc.getText();
            int d1t = Integer.parseInt(tbt);
            int d2t = Integer.parseInt(tbst);

            int rt = (d1t - d2t);

            String resultatt = String.valueOf(rt);

            lreste.setText(resultatt);

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_txtmontantcKeyReleased

    private void txtmontantcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontantcKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontantcKeyPressed

    private void combomodePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combomodePopupMenuWillBecomeInvisible
String tmode = (String) combomode.getSelectedItem();
System.out.println(tmode);
try{
     if (tmode.equals("Chéque")){
        moderegel.setVisible(true);
        cheq.setVisible(true);
     }else{
         moderegel.setVisible(false);
          cheq.setVisible(false);
     }
    
}catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_combomodePopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajoutregelement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajoutregelement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajoutregelement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajoutregelement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajoutregelement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutbtnok;
    private javax.swing.JLabel cheq;
    private javax.swing.JComboBox combomode;
    private com.toedter.calendar.JDateChooser datereglement;
    private javax.swing.JTextField dts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lreste;
    private javax.swing.JTextField moderegel;
    private javax.swing.JTextField txtcin;
    private javax.swing.JTextField txtgsm;
    private javax.swing.JTextField txtmontantc;
    private javax.swing.JTextField txtmttotal;
    private javax.swing.JTextField txtnom;
    private javax.swing.JLabel txtpermis;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
